# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0dacfda76d20422cbae31cbff0928619ad589da76e824f459449090df8b68f90124bbe9111f2b363410f96cf8179b099aa158a849923c5c3dd16c3c90b575259

test:
  secret_key_base: 1cd13a2bfc11713e7ea0896bde4a6f25a6bf0b55104abb9060f001b28962b7763f9a6e683119228f35b1fceea1d4e43995853c83d4d2daf713da82aea7c62939

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
